#!/bin/bash
#SBATCH -A theory
#SBATCH -p batch
#SBATCH -N 1
#SBATCH -J FLEX
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2g
#SBATCH -t 48:00:00
#SBATCH -o ./%j-output.txt
#SBATCH -e ./%j-error.txt

./main

